euraka:
  client:
    register-with-euraka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostnmae: localhost


spring:
  application:
    name: DEPARTMENT-SERVICES